CREATE TABLE IF NOT EXISTS participants_cbomoko (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    submission_id VARCHAR(60) NOT NULL,
    submitted_at DATETIME NOT NULL,
    nom_complet VARCHAR(180) NOT NULL,
    email VARCHAR(190) NOT NULL,
    telephone VARCHAR(60) NOT NULL,
    ville VARCHAR(100) NOT NULL,
    age TINYINT UNSIGNED NOT NULL,
    profession VARCHAR(160) NOT NULL,
    organisation VARCHAR(180) DEFAULT NULL,
    domaine VARCHAR(220) NOT NULL,
    plateformes TEXT NOT NULL,
    liens_plateformes TEXT NOT NULL,
    experience VARCHAR(80) NOT NULL,
    participation_similaire VARCHAR(10) NOT NULL,
    motivation TEXT NOT NULL,
    thematique VARCHAR(240) NOT NULL,
    attentes TEXT NOT NULL,
    disponible_presentiel VARCHAR(10) NOT NULL,
    infos_futures VARCHAR(10) NOT NULL,
    besoins_specifiques VARCHAR(280) NOT NULL,
    source VARCHAR(220) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'nouvelle',
    notes_admin TEXT DEFAULT NULL,
    acces VARCHAR(10) DEFAULT NULL,
    heure_arrive DATETIME DEFAULT NULL,
    ip VARCHAR(80) DEFAULT NULL,
    user_agent VARCHAR(240) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_participants_cbomoko_submission_id (submission_id),
    KEY idx_participants_cbomoko_email (email),
    KEY idx_participants_cbomoko_status (status),
    KEY idx_participants_cbomoko_acces (acces),
    KEY idx_participants_cbomoko_submitted_at (submitted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users_cbomoko (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    full_name VARCHAR(160) NOT NULL,
    email VARCHAR(190) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'admin',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    last_login_at DATETIME DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_users_cbomoko_email (email),
    KEY idx_users_cbomoko_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
